### PR TITLE
Add HD-Wallets

### PR DESCRIPTION
**Pull request by KolbyML**
This PR includes BIP 32, 39, 44. A GUI for setting up mnemonic/hd wallet using mnemonic. Also A RPC and GUI to upgrade non-HD wallets to HD wallets. Using HD wallet you will not be able to cold stake until we implement generating Cold staking addresses as Pivxes implementation makes these separate addresses.

### Setup Mnemonic page

**First page**
This says Phore, but I already fixed that
image

**Restore Page**
You can restore your wallet with mnemonic words
image

**New Wallet Page**
image

**Sort Page**
This page is to make sure they have wrote down their words, it is also so they remember the order as the order of the words is very important
image

### Main Wallet Screen

**HD Status**
I have also added a HD status button, normally I wouldn't bring this up, but yeah just cause I had to add it for the new ui

image

**Wallet Repair**
Her I added a button to upgrade non-HD Wallets to HD. This would also use the wallet startup page just kind of reusing that.

image

### RPC
There are a few changes because of the HD addition, but I also added a new rpc command to upgrade wallets from the client also.

image

### CODE REVIEW

**Comment by akshaynexus** [comment]
will test shortly,and possibly get travis or something going to build it

**Comment by JSKitty** [comment]
utACK, compiling and testing, will report back after testing all features and reviewing code.

**Comment by JSKitty** [comment]
image
A button seems to be invisible here, not sure if this PR introduced the bug.
Although in ZENZO Core v1.3.0 your last CSS changes broke some buttons that needed fixing after merge, perhaps it's the same issue?

**Comment by KolbyML** [comment]
> image
> A button seems to be invisible here, not sure if this PR introduced the bug.
> Although in ZENZO Core v1.3.0 your last CSS changes broke some buttons that needed fixing after merge, perhaps it's the same issue?

That issue was made by @akshaynexus when he rebased

**Comment by akshaynexus** [comment]
Will take a look soonish if that was the cause for missing buttons

**Review by JSKitty — APPROVED** [review]
ACK.
All HD-related functions such as new wallets, old wallet backwards compatibility and non-HD to HD upgrades are all working perfectly on win64 QT.

**Pull request merged**
